

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacciNumber1 = 1
fibonacciNumber2 = 2
fibonacciNumber3 = 0

fibonacciNumbers = [1,2]
count = 0
sumOfNumbers = 0

while (fibonacciNumber3 < 4000000):
    if (fibonacciNumber3 == 0):
        fibonacciNumber1 = 1
        fibonacciNumber2 = 2
    else:
        fibonacciNumber1 = fibonacciNumber2
        fibonacciNumber2 = fibonacciNumber3

    fibonacciNumber3 = fibonacciNumber1 + fibonacciNumber2
    fibonacciNumbers.append(fibonacciNumber3)
    print("number 1: %d, number 2: %s, number 3: %f" % (fibonacciNumber1,fibonacciNumber2, fibonacciNumber3))

print(fibonacciNumbers)

for x in fibonacciNumbers:
    if (fibonacciNumbers[count] % 2 == 0):
        sumOfNumbers += fibonacciNumbers[count]
    count +=1

print(sumOfNumbers)